# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x0cpackage.chat\"(\n\x04User\x12\r\n\x05login\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\")\n\x05Users\x12 \n\x04user\x18\x01 \x03(\x0b\x32\x12.package.chat.User\"}\n\x07Message\x12%\n\tfrom_user\x18\x02 \x01(\x0b\x32\x12.package.chat.User\x12#\n\x07to_user\x18\x03 \x01(\x0b\x32\x12.package.chat.User\x12\x12\n\ncreated_at\x18\x04 \x01(\x02\x12\x0c\n\x04\x62ody\x18\x05 \x01(\tJ\x04\x08\x01\x10\x02\"<\n\x12sendMessageRequest\x12&\n\x07message\x18\x01 \x01(\x0b\x32\x15.package.chat.Message\"\'\n\x13sendMessageResponce\x12\x10\n\x08response\x18\x01 \x01(\t\"6\n\x12getMessagesRequest\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.package.chat.User\"=\n\x13getMessagesResponce\x12&\n\x07message\x18\x01 \x01(\x0b\x32\x15.package.chat.Message\"\x11\n\x0fgetUsersRequest\"6\n\x10getUsersResponce\x12\"\n\x05users\x18\x01 \x01(\x0b\x32\x13.package.chat.Users2\x82\x02\n\x0b\x43hatService\x12R\n\x0bsendMessage\x12 .package.chat.sendMessageRequest\x1a!.package.chat.sendMessageResponce\x12I\n\x08getUsers\x12\x1d.package.chat.getUsersRequest\x1a\x1e.package.chat.getUsersResponce\x12T\n\x0bgetMessages\x12 .package.chat.getMessagesRequest\x1a!.package.chat.getMessagesResponce0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=28
  _USER._serialized_end=68
  _USERS._serialized_start=70
  _USERS._serialized_end=111
  _MESSAGE._serialized_start=113
  _MESSAGE._serialized_end=238
  _SENDMESSAGEREQUEST._serialized_start=240
  _SENDMESSAGEREQUEST._serialized_end=300
  _SENDMESSAGERESPONCE._serialized_start=302
  _SENDMESSAGERESPONCE._serialized_end=341
  _GETMESSAGESREQUEST._serialized_start=343
  _GETMESSAGESREQUEST._serialized_end=397
  _GETMESSAGESRESPONCE._serialized_start=399
  _GETMESSAGESRESPONCE._serialized_end=460
  _GETUSERSREQUEST._serialized_start=462
  _GETUSERSREQUEST._serialized_end=479
  _GETUSERSRESPONCE._serialized_start=481
  _GETUSERSRESPONCE._serialized_end=535
  _CHATSERVICE._serialized_start=538
  _CHATSERVICE._serialized_end=796
# @@protoc_insertion_point(module_scope)
